AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  S3BucketName:
    Type: String
    Default: "raksul-sample"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
  PricingCrawler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./PricingCrawler
      Description: PriceCrawler
      MemorySize: 256
      Timeout: 800
  PricingRegister:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: PricingRegister
      MemorySize: 256
      Timeout: 800
